WebContent/resources/certsurvey.js
WebContent/survey.html

Reset answers now displays a dialog box with the version

Complete implementation of allowing selection of different spec versions

---

WebContent/resources/certsurvey.js
WebContent/styles/styles.css
WebContent/survey.html
src/org/openchain/certification/CertificationServlet.java
src/org/openchain/certification/UserSession.java

Add select version button

---

src/org/openchain/certification/UserSession.java
src/org/openchain/certification/dbdao/SurveyResponseDao.java

Add synchronized methods to prevent possible multi-threading issue for user session and add null pointer checks in the survey DAO.

Fix issue #27

---

README.md

Add back-end localization information in the README file

---

WebContent/admin.html
WebContent/certified.html
WebContent/index.html
WebContent/login.html
WebContent/topnav.html

Code cleaned #91  and issue #88 (Tab not updating on Edit Conformance Dialog Box) fixed.

Code cleaned with tab issue fixed

---

WebContent/resources/global.js
WebContent/resources/locales/ru/translation.json
WebContent/resources/navbar.js
WebContent/signup.html
WebContent/styles/newstyle.css
WebContent/topnav.html

Issue #24 Add user preference for language and Issue #93 Increase logo size was fixed

Language profile update

---

WebContent/resources/global.js

Fix issue #100 - remove reference to unused language variable

---

WebContent/resources/global.js
WebContent/topnav.html

This is not a complete fix.  It display a dialog, but the formatting is off and there is no title.

Partial fix for missing error handling

---

resources/messages.properties
resources/messages_ru.properties
src/org/openchain/certification/I18N.java

Fix bad string formatting and improve the error handling for the back-end I18N code

---

WebContent/admin.html
WebContent/certified.html
WebContent/footer.html
WebContent/index.html
WebContent/resources/admin.js
WebContent/resources/global.js
WebContent/resources/locales/en/translation.json
WebContent/resources/locales/ru/translation.json
WebContent/resources/navbar.js
WebContent/signup.html
WebContent/styles/newstyle.css
WebContent/topnav.html

String fragments causing localization issues was fixed and alert was removed for Update questionnaire tab.

String format fix

---

WebContent/admin.html
WebContent/resources/admin.js
WebContent/resources/certsurvey.js
WebContent/resources/locales/en/translation.json
WebContent/resources/locales/ru/translation.json
WebContent/resources/navbar.js
WebContent/styles/newstyle.css

Error dialog fix

---

resources/messages.properties
src/org/openchain/certification/CertificationServlet.java
src/org/openchain/certification/UserSession.java
src/org/openchain/certification/model/SurveyResponse.java

Update the survey language when changing the language in the UI

Update survey language

---

WebContent/pwreset.html
WebContent/resources/certified.js
WebContent/resources/certsurvey.js
WebContent/resources/pwreset.js
WebContent/styles/newstyle.css
WebContent/styles/styles.css

Code Review

---

WebContent/resources/certsurvey.js

I fixed the JavaScript which generated some bad HTML (extra quote, spaces in an ID).
This may have fixed issue #122

Remove extra quote

---

WebContent/resources/admin.js

Change data table page size from 5 to 15 on the admin pages

---

WebContent/resources/locales/en/translation.json
WebContent/resources/locales/ja/translation.json

Resolves issue #133 
Resolves issue #134

Resolve UI issues discovered in production testing

---

src/org/openchain/certification/UserSession.java
src/org/openchain/certification/dbdao/SurveyResponseDao.java
src/org/openchain/certification/utility/EmailUtility.java
test/org/openchain/certification/TestUserSession.java
test/org/openchain/certification/dbdao/TestSurveyResponseDao.java

Resolve issues #136, #135 and an issue submitting surveys when multiple languages exist

---

WebContent/pwreset.html

Resolve issue #139 - 500 error during password reset

---

WebContent/resources/locales/ja/translation.json

Resolve OK string translation in the select conformance questionnaire version dialog

Ok button Fix : Resolves #132

---

WebContent/index.html
WebContent/resources/locales/en/translation.json

Suggested major update including a video gate.

added updated index.html

---

WebContent/resources/navbar.js

Fix issue #152 unable to resend verification

---

resources/messages.properties
resources/messages_ja.properties
src/org/openchain/certification/CertificationServlet.java
src/org/openchain/certification/dbdao/SurveyDbDao.java
src/org/openchain/certification/model/Question.java
src/org/openchain/certification/model/SubQuestion.java
src/org/openchain/certification/model/Survey.java
src/org/openchain/certification/model/YesNoNotApplicableQuestion.java
src/org/openchain/certification/model/YesNoQuestion.java
src/org/openchain/certification/model/YesNoQuestionWithEvidence.java
test/org/openchain/certification/TestQuestionJsonDeserializer.java
test/org/openchain/certification/TestSurveyQuestionUpdateStats.java
test/org/openchain/certification/TestUpdateSurvey.java
test/org/openchain/certification/TestUserSession.java
test/org/openchain/certification/dbdao/TestSurveyDbDao.java
test/org/openchain/certification/dbdao/TestSurveyResponseDao.java
test/org/openchain/certification/model/TestQuestion.java
test/org/openchain/certification/model/TestSection.java
test/org/openchain/certification/model/TestSubquestion.java
test/org/openchain/certification/model/TestSurvey.java
test/org/openchain/certification/model/TestYesNoNotApplicableQuestion.java
test/org/openchain/certification/model/TestYesNoQuestion.java
test/org/openchain/certification/model/YesNoQuestionWithEvidenceTest.java
testresources/dup_question_questionnaire.json
testresources/oneless_questionnaire.json
testresources/updated_questionnaire.json
testresources/valid_questionnaire.json

Resolves issue #145 
Includes some refactoring of questions to support validation.

Add validation and fix various bugs related to survey updates

---

WebContent/resources/navbar.js

This likely fixes issue #148  Although, it can not be verified since the issue cannot be reliably reproduced.

Load references to the menu bar after the HTML has been loaded.  

---

WebContent/topnav.html

Fix issue #156 - URL link for the openchain logo

---

WebContent/index.html
WebContent/resources/locales/en/translation.json

Fix bad HTML on index page

---

src/org/openchain/certification/utility/EmailUtility.java

I got tired of getting emails about "cerification" requests ;)

fix annoying typo in admin email

---

src/org/openchain/certification/utility/EmailUtility.java
src/org/openchain/certification/utility/PasswordManualReset.java

Add password reset command line utility

---

WebContent/resources/certsurvey.js
src/org/openchain/certification/CertificationServlet.java

Resolve issue #184 - replace invalid characters in section name

---

WebContent/resources/admin.js
resources/messages.properties
resources/messages_ja.properties
resources/messages_ko.properties
resources/messages_ru.properties
src/org/openchain/certification/CertificationServlet.java
src/org/openchain/certification/SurveyQuestionUpdateStats.java
src/org/openchain/certification/SurveyUpdateResult.java
src/org/openchain/certification/dbdao/SurveyDbDao.java
test/org/openchain/certification/TestSurveyQuestionUpdateStats.java
test/org/openchain/certification/TestUpdateSurvey.java
test/org/openchain/certification/dbdao/TestSurveyDbDao.java
testresources/duplicatedlocale/valid_questionnaire_en.json
testresources/duplicatedlocale/valid_questionnaire_ja.json
testresources/duplicatedlocale/valid_questionnaire_ja2.json
testresources/multiplevalidquestionnaires/valid_questionnaire_en.json
testresources/multiplevalidquestionnaires/valid_questionnaire_ja.json
testresources/multiplevalidquestionnaires/valid_questionnaire_ko.json
testresources/questionsmissmatched/valid_questionnaire_en.json
testresources/questionsmissmatched/valid_questionnaire_ja.json
testresources/questionsmissmatched/valid_questionnaire_ko.json
testresources/updated_questionnaire.json
testresources/updated_section_question_questionnaire.json

Update section titles

---

WebContent/resources/locales/ja/translation.json

Add Japanese translation for Yes

---

src/org/openchain/certification/UserSession.java
src/org/openchain/certification/utility/EmailUtility.java

Add organization name and specification version to the email sent to admins notifying new submissions
Resolves issue #191 

Additional information to conforming submissions email

---

WebContent/resources/certsurvey.js
WebContent/survey.html

Add ISO title to OpenChain certification questionnaire

---

WebContent/resources/locales/ja/translation.json
src/org/openchain/certification/dbdao/SurveyResponseDao.java

Does not solve issue #210 but it will throw the error earlier to help identify the root cause
also add fix links for translated PDF questionnaires

Add a check for duplicate responses

---

src/org/openchain/certification/UserSession.java
src/org/openchain/certification/dbdao/SurveyResponseDao.java
test/org/openchain/certification/dbdao/TestSurveyResponseDao.java

Helps avoid possible duplicate responses as in issue #210 

Change delete response answers to user the username and spec version

---

README.md
WebContent/login.html
WebContent/pwreset.html
WebContent/resources/navbar.js
WebContent/resources/pwreset.js
WebContent/signup.html
resources/messages.properties
resources/messages_ja.properties
resources/messages_ko.properties
src/org/openchain/certification/CertificationServlet.java
src/org/openchain/certification/ReCaptcha.java
src/org/openchain/certification/ReCaptchaException.java
src/org/openchain/certification/ReCaptchaResponse.java
src/org/openchain/certification/RequestJson.java
src/org/openchain/certification/UserSession.java

Add ReCaptcha functionality to prevent robo attacks on the website.

Add ReCaptcha functionality

---

WebContent/footer.html
WebContent/resources/locales/en/translation.json
WebContent/resources/locales/ja/translation.json
WebContent/resources/locales/ko/translation.json
WebContent/resources/locales/ru/translation.json

Add captcha notice and terms

---

WebContent/footer.html
WebContent/login.html

Fixes a UI spacing issue on the login page

Change spacing in footer

---

WebContent/resources/navbar.js

partial resolution for issue #221
Doesn't solve the translation of bad usernames, but it will display
the error in english.

Add text in HTML for signup errors

---

WebContent/login.html
WebContent/pwreset.html
WebContent/signup.html
src/org/openchain/certification/CertificationServlet.java
src/org/openchain/certification/ReCaptcha.java

Change URL for reCAPTCH
